ci:
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'ci(pre-commit): pre-commit.ci autoupdate'
  autofix_commit_msg: 'ci(pre-commit): pre-commit.ci autofixes'


repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit
          - pre-push

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        exclude: ^docs/
