ci:
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'ci(pre-commit): pre-commit.ci autoupdate'
  autofix_commit_msg: 'ci(pre-commit): pre-commit.ci autofixes'


repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.2.2
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit
          - push

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.270
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        exclude: ^docs/
