name: CI

on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pdm sync -d -G test

      - name: Run Tests
        run: pdm run cover -v --force-sugar --color=yes

      - name: Upload coverage report to Codecov
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: 0ab7b87f48eece5e7a9f168d609bab59554054984691917240d1dedbcf2d7cba
        with:
          coverageLocations: reports/coverage.xml:coverage.py
